name: Run Tests

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install ffmpeg
        run: |
          sudo apt update && sudo apt install -y ffmpeg

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]

      - name: Run tests
        run: pytest
